[exchange]
symbols = ["BTCUSDT"]

[websocket]
url = "wss://wbs-api.mexc.com/ws"
ping_interval_secs = 15
# nur "100ms" oder "10ms"
depth_interval = "100ms"

[logging]
level = "INFO"
save_logs = true
log_file_path = "logs/app.log"
rewrite_last_logs = false
